language: go

go:
  - 1.8
  - 1.9
  - master

env:
  - DEP_VERSION="0.3.2"

matrix:
  allow_failures:
    go: master
    fast_finish: true

script:
  - "make travis"

notifications:
  email:
    - jmurray@appnexus.com
  on_success: change
  on_failure: always

before_install:
  - go get -u github.com/golang/lint/golint
  - go get -u github.com/jstemmer/gotags
  # Download the binary to bin folder in $GOPATH
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  # Make the binary executable
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure

after_success:
  - bash <(curl -s https://codecov.io/bash)
